### ISSUE TITLE
npm run build:portal "compiles" with errors

### ISSUE THREAD

**Issue by jonathanagosto** [formio/formio#2064]
## Short Summary

Running `npm run build:portal` "compiles" with errors.

## Is there an existing issue for this problem?

[x] I have searched the existing issues

## FormIO Version

4.5.2 (`main` branch: commit 8e0d58e9852b1c39a592b39b8c79fcc76c484045)

## Operating System (OS)

Mac OS Tahoe 26.0.1

## How to reproduce

1. `git clone git@github.com:formio/formio.git`
2. `yarn` & `npm run build:portal`

Actual results

```
% npm run build:portal

> formio@4.5.2 build:portal
> cd portal && yarn && yarn build && cd ..

➤ YN0000: · Yarn 4.10.3
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ eslint is listed by your project with version 9.37.0 (p759c1d), which doesn't satisfy what @typescript-eslint/eslint-plugin and other dependencies request (^8.57.0).
➤ YN0002: │ oss-portal@workspace:. doesn't provide vite (p7333e7), requested by @vitejs/plugin-react.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 290ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 0s 505ms
assets by status 4.3 MiB [cached] 5 assets
assets by status 257 KiB [compared for emit]
  assets by path *.svg 21.1 KiB
    asset icon-resource.svg 8.96 KiB [compared for emit] [from: public/icon-resource.svg] [copied]
    asset logo-formio-horizontal-lightbg.svg 5.4 KiB [compared for emit] [from: public/logo-formio-horizontal-lightbg.svg] [copied]
    asset icon-formio-small.svg 3.88 KiB [compared for emit] [from: public/icon-formio-small.svg] [copied]
    asset icon-form.svg 2.84 KiB [compared for emit] [from: public/icon-form.svg] [copied]
  assets by path *.css 221 KiB
    asset formio.full.min.css 128 KiB [compared for emit] [from: public/formio.full.min.css] [copied]
    asset style.css 92.8 KiB [compared for emit] [from: public/style.css] [copied]
  asset favicon.png 13.8 KiB [compared for emit] [from: public/favicon.png] [copied]
  asset index.html 854 bytes [compared for emit] [from: public/index.html] [copied]
asset bundle.js 7.08 MiB [emitted] (name: main)
runtime modules 4.02 KiB 12 modules
orphan modules 443 bytes [orphan] 1 module
modules by path ./node_modules/ 5.96 MiB (javascript) 4.3 MiB (asset)
  javascript modules 5.96 MiB 1289 modules
  asset modules 4.3 MiB (asset) 210 bytes (javascript)
    ./node_modules/remixicon/fonts/remixicon.eot?t=1760071648894 579 KiB (asset) 42 bytes (javascript) [built] [code generated]
    ./node_modules/remixicon/fonts/remixicon.woff2?t=1760071648894 178 KiB (asset) 42 bytes (javascript) [built] [code generated]
    + 3 modules
modules by path ./src/ 77.9 KiB
  modules by path ./src/components/ 70.2 KiB 19 modules
  modules by path ./src/module/*.ts 5.82 KiB 2 modules
  modules by path ./src/hooks/*.tsx 1.14 KiB 2 modules
  ./src/index.tsx 751 bytes [built] [code generated]
./package.json 1.26 KiB [built] [code generated]

ERROR in /path/to/formio/portal/src/components/FormView/FormAccess.tsx
./src/components/FormView/FormAccess.tsx 272:12-17
[tsl] ERROR in /path/to/formio/portal/src/components/FormView/FormAccess.tsx(272,13)
      TS2352: Conversion of type '{ display: "form"; components: ({ type: string; key: string; input: true; components: ({ label: string; labelPosition: string; widget: string; tableView: true; multiple: true; dataSrc: "values"; data: { ...; }; ... 6 more ...; input: true; } | { ...; })[]; } | { ...; })[]; }' to type 'Form' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of property 'components' are incompatible.
    Type '({ type: string; key: string; input: true; components: ({ label: string; labelPosition: string; widget: string; tableView: true; multiple: true; dataSrc: "values"; data: { values: { label: string; value: string; }[]; }; ... 6 more ...; input: true; } | { ...; })[]; } | { ...; })[]' is not comparable to type 'Component[]'.
      Type '{ type: string; key: string; input: true; components: ({ label: string; labelPosition: string; widget: string; tableView: true; multiple: true; dataSrc: "values"; data: { values: { label: string; value: string; }[]; }; ... 6 more ...; input: true; } | { ...; })[]; } | { ...; }' is not comparable to type 'Component'.
        Object literal may only specify known properties, and 'event' does not exist in type 'Component'.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/components/FormView/index.tsx 18:0-42 46:2342-2352
 @ ./src/components/App.tsx 9:0-38 25:804-812 31:314-322
 @ ./src/index.tsx 7:0-35 16:145-148

ERROR in /path/to/formio/portal/src/components/FormView/FormActions.tsx
./src/components/FormView/FormActions.tsx 159:40-45
[tsl] ERROR in /path/to/formio/portal/src/components/FormView/FormActions.tsx(159,41)
      TS2339: Property 'event' does not exist on type 'ButtonComponent'.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/components/FormView/index.tsx 17:0-44 46:2417-2428
 @ ./src/components/App.tsx 9:0-38 25:804-812 31:314-322
 @ ./src/index.tsx 7:0-35 16:145-148

webpack 5.102.1 compiled with 2 errors in 3153 ms
```
## Expected results

The command should run without errors.

## Anything else?

From my brief look up, it seems to me that this error was introduced in commit 8e0d58e9852b1c39a592b39b8c79fcc76c484045
